### ISSUE TITLE
about your canopen and canopen of canfestival

### ISSUE THREAD

**Issue by samini3000** [marel-keytech/openCANopen#1]
I was recently using canopen of canfestival and I faced a problem.
my problem: when I want to handle multiple buses on the same program, I forced to define a object dictionary for each bus( a .h and .c for each bus) and my program have about 60 number of bus.
does your library handle this?
canfestival has a good objectdictgen that atomatically initialize variables, callbacks, sdo and pdo . do you have automatic object dictionary generator?

**Comment by any1** [comment]
You need to run one process per bus. I am curious why you need to have 60 buses.
We do not have a code generator for the object dictionary. The object dictionary is written in code.

**Comment by samini3000** [comment]
assume you want to have a central unit for monitoring of all your CAN devices.
in your code you mean I should have a *co_drv for each bus?
do you have a document for using the code?
can I find a sample that a master send sdo msg  and another master get event on receive that and receive sdo msg ?
can I add new drivers ?
Thanks for your patience and response

**Comment by samini3000** [comment]
Actually these buses are on different lines

**Comment by any1** [comment]
If these devices send the information that you are interested in periodically either via PDO or SDO, you can monitor them passively.
The canopen-dump utility does just that. PDO is easy because the communication protocol is state-less. For SDO, the monitor must be aware of the state.
