### ISSUE TITLE
Non-socket CAN interface

### ISSUE THREAD

**Issue by ess-gsmith** [marel-keytech/openCANopen#2]
I like the relative simplicity of using openCANopen. Would it be possible to use it with a non-socket CAN interface? For example, a shared library with functions for open, ioctl, read, write, etc.? The purpose would be to use a particular Ethernet to CAN adapter that has a closed source library provided.

**Comment by any1** [comment]
I would not try to override these functions as they are quite essential to the standard C library.
There is an abstraction for socket communication in [src/sock.c](https://github.com/marel-keytech/openCANopen/blob/master/src/sock.c). It already supports TCP for bridging and testing purposes.
